package solanerrors

var pumpFunErrors = map[int]string{
	6000: "Not authorized to execute this instruction",
	6001: "Program already initialized",
	6002: "Slippage: too much SOL required to buy — increase slippage or reduce amount",
	6003: "Slippage: too little SOL received from sell — increase slippage or reduce amount",
	6004: "Token mint does not match bonding curve",
	6005: "Token has graduated to Raydium — bonding curve complete",
	6006: "Bonding curve not complete",
	6007: "Program not initialized",
	6008: "Withdraw too frequent",
	6009: "Invalid new size",
	6010: "Account type not supported",
	6011: "Invalid initial token reserves",
	6012: "Invalid virtual token reserves",
	6013: "Fee basis points exceed maximum",
	6014: "Invalid withdraw authority",
	6015: "Invalid pool migration fee",
	6016: "Pool migration fee too low",
	6017: "Withdraw instruction disabled",
	6018: "Migrate instruction disabled",
	6019: "Invalid creator pubkey",
	6020: "Cannot buy zero tokens",
	6021: "Not enough tokens available to buy",
	6022: "Cannot sell zero tokens",
	6023: "Not enough tokens to sell",
	6024: "Arithmetic overflow",
	6025: "Arithmetic truncation",
	6026: "Division by zero",
	6027: "Not enough remaining accounts",
	6028: "All fee recipients must be non-zero",
	6029: "Fee recipients must be sorted and unique",
	6030: "Creator address cannot be zero",
	6031: "Start time is in the past",
	6032: "End time is in the past",
	6033: "End time must be after start time",
	6034: "Time range too large",
	6035: "End time before current day",
	6036: "Supply update for finished range",
	6037: "Day index after end index",
	6038: "Day is in active range",
	6039: "Invalid incentive mint",
	6040: "Not enough SOL to cover rent exemption",
	6041: "Not enough SOL to cover fees",
	6042: "Slippage: would receive fewer tokens than expected minimum",
	6043: "Token name too long",
	6044: "Token symbol too long",
	6045: "Token URI too long",
	6046: "CreateV2 is disabled",
	6047: "Initialization failed",
	6048: "Mayhem mode disabled",
}
